version: '3.8'

services:
  lm-webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: lm-webapp
    depends_on:
      - lm-database
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=LibraryDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"

  lm-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
