version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Map port 80 trong container ra port 8080 trên host
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=LibraryManagerDB;User=sa;Password=YourStrong@Passw0rd;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433" # SQL Server chạy trên port mặc định
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd" # Password mạnh cho user `sa`
      ACCEPT_EULA: "Y" # Chấp nhận EULA
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
